### PR TITLE
fix: Inversion of custom regions

### LINKED ISSUE #1925: Inverting a CustomRegion has no effect
**Describe the bug**
Selecting the "Invert" option in `CustomRegionProcedureNode` has no effect!

### PR DESCRIPTION
**Pull request by trisyoungs**
Addresses a failure of `RegionProcedureNodeBase` which did precisely nothing with its `invert_` variable.

Closes #1925.

### CODE REVIEW

File: src/classes/region.cpp [hunk 1]
```diff
@@ -26,9 +26,9 @@ bool Region::generate(const Configuration *cfg, double voxelSize,
     auto voxelCheckFunction = [&](auto triplet, auto x, auto y, auto z)
     {
         voxelMap_[triplet] = {Vec3<int>(x, y, z),
-                              voxelCombinable.local()->isVoxelValid(
-                                  cfg, box_->getReal({(x + 0.5) * voxelSizeFrac_.x, (y + 0.5) * voxelSizeFrac_.y,
-                                                      (z + 0.5) * voxelSizeFrac_.z}))};
+                              invert != voxelCombinable.local()->isVoxelValid(
+                                            cfg, box_->getReal({(x + 0.5) * voxelSizeFrac_.x, (y + 0.5) * voxelSizeFrac_.y,
+                                                                (z + 0.5) * voxelSizeFrac_.z}))};
```
Comment (jws-1) [inline src/classes/region.cpp:31]: Nice.

**Review by jws-1 — APPROVED** [review]
Works! :+1:
