### PR TITLE
Elapsed Timer Fix- zero on each run, update status label

### LINKED ISSUE #1707: Stopped simulation doesn't update status bar / time elapsed label
**Describe the bug**
Stopping the simulation through the main menu `Stop` doesn't update the status bar, so even when it's actually stopped it still shows "Running (ESC to stop)" and the time elapsed string.

**Operating System:**
- IDAaaS

### PR DESCRIPTION
**Pull request by rhinoella**
The status bar is updated so that:
- Timer resets to zero on the start of each run
- The status label bug is fixed: said Dissolve was still running despite stopped

Closes #1707.

### CODE REVIEW

File: src/gui/guiFuncs.cpp [hunk 1]
```diff
@@ -316,6 +316,8 @@ void DissolveWindow::updateStatusBar()
     }
     else if (!dissolveIterating_ && elapsedTimer_.secondsElapsed() > 0.0)
     {
+        statusLabel_->setText("Idle");
```
Comment (trisyoungs) [inline src/gui/guiFuncs.cpp]: Just a small suggestion, since this reflects when a simulation has been stopped after being actively run in the current GUI session.
```suggestion
        statusLabel_->setText("Stopped");
```

**Review by trisyoungs — APPROVED** [review]
:+1:
