### PR TITLE
fix: Remove atom type and master term from forcefield tab

### LINKED ISSUE #1065: Remove Master Terms from GUI
**Describe the feature / issue**
It is currently not possible to remove defined master terms from the GUI, as the necessary functionality in the derived `MasterTermTreeModel`s does not exist. When implemented, we also must call the relevant detach function in all current `Species`.

### LINKED ISSUE #1586: Cannot remove Atom Types
The Duplicate/Add buttons work as expected, but the remove button is disabled.
image

### LINKED ISSUE #1874: Cannot delete Atom Type and Master Terms
**Describe the bug**
Cannot remove atom type or master terms (can add and duplicate)

**To Reproduce**
1. Import species from LigParGen without "simplify atom types"
2. Try to manually delete duplicating Atom Types

**Expected behaviour**
To be able to remove redundant atom types (and master terms) if the selected atom type is not used in any existing species.

**Operating System:**
 - OS:  Linux
 - OS version / flavour:  IDAaaS

### PR DESCRIPTION
**Pull request by RobBuchananCompPhys**
Closes #1065, Closes #1874, Closes #1586

### CODE REVIEW

File: src/gui/forcefieldTab.cpp [hunk 1]
```diff
@@ -470,6 +510,26 @@ void ForcefieldTab::masterImpropersDataChanged(const QModelIndex &, const QModel
     dissolveWindow_->setModified();
 }
 
+void ForcefieldTab::masterBondsSelectionChanged(const QItemSelection &current, const QItemSelection &previous)
+{
+    ui_.MasterTermRemoveBondButton->setEnabled(!current.empty());
```
Comment (trisyoungs) [inline src/gui/forcefieldTab.cpp:515]: I use code exactly like this, but there is a small bug somewhere whereby if you delete the last bond or angle the button remains enabled, despite there being no current selection.  Not a merge-killer, but may be worth taking a few minutes to try and figure out.

File: src/gui/forcefieldTab.cpp [hunk 2]
```diff
@@ -479,7 +539,36 @@ void ForcefieldTab::on_MasterTermAddBondButton_clicked(bool checked)
     dissolveWindow_->setModified();
 }
 
-void ForcefieldTab::on_MasterTermRemoveBondButton_clicked(bool checked) { Messenger::error("NOT IMPLEMENTED YET.\n"); }
+void ForcefieldTab::on_MasterTermRemoveBondButton_clicked(bool checked)
+{
+    QMessageBox queryBox;
+    queryBox.setWindowTitle(QString("Remove Master Bond"));
+    queryBox.setText(QString("This operation cannot be undone!"));
```
Comment (trisyoungs) [inline src/gui/forcefieldTab.cpp]: Worth elaborating here a bit and elsewhere (and reformatting because this will no doubt break the CI!):
```suggestion
    queryBox.setText(QString("Are you sure? This operation cannot be undone!\nANy uses of this term in species will be converted to a local definition."));
```

**Review by trisyoungs — COMMENTED** [review]
Very close.  Just a bit of tweaking required!

File: src/gui/forcefieldTab.cpp [hunk 3]
```diff
@@ -479,7 +543,40 @@ void ForcefieldTab::on_MasterTermAddBondButton_clicked(bool checked)
...
+
+    if (queryBox.exec() != QMessageBox::Yes)
+        return;
+
+    if (dissolve_.coreData().nMasterBonds() == 1)
+        ui_.MasterTermRemoveBondButton->setEnabled(false);
+
+    auto index = ui_.MasterBondsTable->currentIndex();
+    if (!index.isValid())
+        return;
```
Comment (trisyoungs) [inline src/gui/forcefieldTab.cpp]: Need to do the check for a valid index first so we don't needlessly create & present user choice. Also, not sure what the `if (dissolve_.coreData().nMasterBonds() == 1)` was achieving, so removed it! This change can propagate to the other term types.
```suggestion
    auto index = ui_.MasterBondsTable->currentIndex();
    if (!index.isValid())
        return;

    QMessageBox queryBox;
    queryBox.setWindowTitle(QString("Remove Master Bond"));
    queryBox.setText(QString("Are you sure? This operation cannot be undone!\n") +
                     QString("Any uses of this term in species will be converted to a local definition."));
    queryBox.setInformativeText("Proceed?");
    queryBox.setStandardButtons(QMessageBox::Yes | QMessageBox::No);
    queryBox.setDefaultButton(QMessageBox::No);

    if (queryBox.exec() != QMessageBox::Yes)
        return;
```

**Review by trisyoungs — APPROVED** [review]
Looks good.  Just a bit of cleanup / ordering of operations as detailed in the comment.

File: src/gui/forcefieldTab.cpp (hunk 3 above)
Comment (RobBuchananCompPhys) [reply src/gui/forcefieldTab.cpp]: `if (dissolve_.coreData().nMasterBonds() == 1)` was meant to disable the remove button if we are removing the last bond/angle/... etc.
Did this not solve an issue we had previously discussed where the remove button remained enabled after removing all items?

Comment (trisyoungs) [reply src/gui/forcefieldTab.cpp]: Oh, I see - sorry.  Not really with it in the logic sense today!

Let's go with this solution for now, but hopefully will be able to revert it in the follow-up PR.
