### PR TITLE
1710 default config populations

### LINKED ISSUE #1205: Prevent use of coordinate sets in add configuration wizard
**Describe the feature / issue**
An option to prevent any use of `CoordinateSets` nodes in the Add Configuration Wizard would be useful.

### LINKED ISSUE #1710: Change default populations in add configuration wizard
**Describe the bug**
The add configuration wizard makes a clumsy attempt at setting "relevant" species populations based on the size of the molecules selected (i.e. the relative number of atoms in each).   This is frankly a terrible idea, and we shouldn't do it as it just introduces confusion (and breaks the Emim-OAc tutorial!).

We should just default to populations of `1` in all cases.

### PR DESCRIPTION
**Pull request by trisyoungs**
A quick PR to address a couple of things with the Add Configuration Wizard, improving UX.

Closes #1710.
Closes #1205.

### CODE REVIEW

File: src/gui/models/addSpeciesInfoModel.cpp [hunk 1]
```diff
@@ -70,16 +71,23 @@ QVariant AddSpeciesInfoModel::data(const QModelIndex &index, int role) const
...
+    {
+        switch (index.column())
+        {
             case (AddSpeciesInfo::Rotate):
-                return speciesInfo_[index.row()].rotate();
+                return speciesInfo_[index.row()].rotate() ? Qt::Checked : Qt::Unchecked;
             case (AddSpeciesInfo::UseCoordinateSets):
-                return speciesInfo_[index.row()].useCoordinateSets();
+                return speciesInfo_[index.row()].useCoordinateSets() ? Qt::Checked : Qt::Unchecked;
+                ;
```
Comment (rhinoella) [inline src/gui/models/addSpeciesInfoModel.cpp]:
```suggestion
```

**Review by rhinoella — APPROVED** [review]
👍
